# config_islandviewer.yaml

# Input directory containing .gbk files
input_folder: "/path/to/your//Genomes"

# Output directory for IslandViewer results
output_folder: "Island4" 

# IslandViewer script path (modify if needed)
islandviewer_script: "/path/to/IslandViewer2.py"

