# config_HGTector2.yaml

input_dir: "output_faa_2"  # Input proteome directory
search_dir: "/root/search_dir/test_mainflow"  # Intermediate search step directory
analyze_dir: "/root/analyze_dir/test_mainflow"  # Final results directory

database:
  diamond_db: "/root/database/diamond/db/db.dmnd"
  taxdump: "database/hgtdb_20230102/taxdump/"

hgtector:
  threads: 7  # Adjust based on available resources
  conda_env: "/root/anaconda3/envs/hgtector"

analysis_params:
  bandwidth: "grid"
  donor_name: true
  evalue: 1e-50
  identity: 50
  coverage: 50
  silhouette: 0
  noise: 0

